baseURL = 'https://hopesfill.com/'
languageCode = 'zh-cn'
title = "john's daily does"
theme = 'PaperMod'

author = "hopesfill"

[params]
  author = "hopesfill"

[params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"